// Catálogo enriquecido — añade barrio, openNow, delivery, payments, categoryId
const CATEGORIES = [
  { id: 'restaurantes', name: 'Restaurantes',    code: 'RE', count: 42 },
  { id: 'tiendas',      name: 'Tiendas',         code: 'TI', count: 38 },
  { id: 'ropa',         name: 'Ropa & Calzado',  code: 'RO', count: 27 },
  { id: 'salud',        name: 'Salud',           code: 'SA', count: 19 },
  { id: 'talleres',     name: 'Talleres',        code: 'TA', count: 23 },
  { id: 'belleza',      name: 'Belleza',         code: 'BE', count: 31 },
  { id: 'panaderia',    name: 'Panadería',       code: 'PA', count: 14 },
  { id: 'electronicos', name: 'Electrónicos',    code: 'EL', count: 18 },
  { id: 'educacion',    name: 'Educación',       code: 'ED', count: 12 },
  { id: 'transporte',   name: 'Transporte',      code: 'TR', count: 9  },
  { id: 'artesania',    name: 'Artesanías',      code: 'AR', count: 16 },
  { id: 'frutas',       name: 'Frutas & Verduras', code: 'FR', count: 21 },
  { id: 'tecnologia',   name: 'Tecnología',      code: 'TC', count: 15 },
  { id: 'eventos',      name: 'Eventos',         code: 'EV', count: 8  },
];

const BARRIOS = ['La Esperanza', 'El Centro', 'Villa Rosa', 'El Prado', 'Barrio Norte', 'Barrio Nuevo', 'La Paz', 'Alegría'];

const BUSINESSES = [
  { id: 1, cat: 'restaurantes', name: 'La Sazón de Doña Rosa', owner: 'Rosa Martínez', desc: 'Comida casera con los mejores sabores de la región. Menú del día con sopa, segundo y jugo natural.', rating: 4.8, reviews: 124, address: 'Calle 12 #34-56', barrio: 'La Esperanza', phone: '311 234 5678', whatsapp: true, hours: 'Lun–Sáb · 8:00–16:00', openNow: true, closesAt: '4pm', specialty: 'Menú del día', tags: ['Comida casera', 'Domicilio'], payments: ['Efectivo', 'Nequi'], verified: true, since: '2018', priceLevel: 1 },
  { id: 2, cat: 'restaurantes', name: 'El Fogón Criollo', owner: 'Carlos Pedraza', desc: 'Especialidad en asados y fritanga. Ambiente familiar y precios populares para toda la familia.', rating: 4.6, reviews: 89, address: 'Av. Popular #12-20', barrio: 'El Centro', phone: '320 456 7890', whatsapp: true, hours: 'Vie–Dom · 11:00–22:00', openNow: false, closesAt: null, specialty: 'Fritanga', tags: ['Parrilla', 'Para llevar'], payments: ['Efectivo', 'Daviplata'], verified: false, since: '2021', priceLevel: 2 },
  { id: 3, cat: 'restaurantes', name: 'Sabores del Valle', owner: 'Lucía Rondón', desc: 'Platos típicos de la región andina. Bandeja paisa, ajiaco santafereño y postres artesanales.', rating: 4.9, reviews: 203, address: 'Carrera 5 #8-90', barrio: 'Barrio Nuevo', phone: '301 678 9012', whatsapp: true, hours: 'Todos los días · 7:00–21:00', openNow: true, closesAt: '9pm', specialty: 'Bandeja paisa', tags: ['Regional', 'Domicilio', 'Reservas'], payments: ['Efectivo', 'Nequi', 'Tarjeta'], verified: true, since: '2015', priceLevel: 2 },
  { id: 4, cat: 'restaurantes', name: 'Tacos Don Memo', owner: 'Guillermo Flores', desc: 'Auténtica cocina mexicana adaptada al paladar local. Tacos, burritos y salsas caseras.', rating: 4.5, reviews: 67, address: 'Diagonal 45 #23-10', barrio: 'Barrio Norte', phone: '315 890 1234', whatsapp: false, hours: 'Lun–Sáb · 12:00–21:00', openNow: true, closesAt: '9pm', specialty: 'Tacos al pastor', tags: ['Mexicana', 'Para llevar'], payments: ['Efectivo'], verified: false, since: '2022', priceLevel: 1 },
  { id: 5, cat: 'restaurantes', name: 'Caldo de Pollo Mama Juanita', owner: 'Juanita Sánchez', desc: 'Caldos, sancochos y sopas preparados con recetas de abuela. El mejor remedio para cualquier día.', rating: 4.7, reviews: 156, address: 'Calle 23 #45-67', barrio: 'Villa Rosa', phone: '317 012 3456', whatsapp: true, hours: 'Lun–Dom · 6:00–15:00', openNow: true, closesAt: '3pm', specialty: 'Sancocho de gallina', tags: ['Sopas', 'Desayunos'], payments: ['Efectivo', 'Nequi'], verified: true, since: '2010', priceLevel: 1 },
  { id: 6, cat: 'restaurantes', name: 'Pizzas al Carbón', owner: 'Fernando Castro', desc: 'Pizzas artesanales horneadas en leña. Masa madre, ingredientes frescos y sabor auténtico.', rating: 4.4, reviews: 44, address: 'Calle 7 #12-34', barrio: 'Barrio Norte', phone: '310 234 5678', whatsapp: true, hours: 'Mié–Dom · 17:00–23:00', openNow: false, closesAt: null, specialty: 'Pizza artesanal', tags: ['Italiana', 'Domicilio'], payments: ['Efectivo', 'Nequi', 'Tarjeta'], verified: false, since: '2023', priceLevel: 2 },
  { id: 7, cat: 'tiendas', name: 'Tienda El Progreso', owner: 'Marlene Ríos', desc: 'Todo lo que necesitas para el hogar. Abarrotes, aseo y más. Fiado a clientes frecuentes.', rating: 4.7, reviews: 211, address: 'Carrera 8 #15-30', barrio: 'La Esperanza', phone: '312 345 6789', whatsapp: false, hours: 'Lun–Dom · 6:00–22:00', openNow: true, closesAt: '10pm', specialty: 'Abarrotes', tags: ['General', 'Fiado'], payments: ['Efectivo', 'Nequi'], verified: true, since: '2005', priceLevel: 1 },
  { id: 8, cat: 'tiendas', name: 'Minimercado La Victoria', owner: 'Pedro Gómez', desc: 'Productos frescos, carnes y lácteos directos del proveedor. Precios justos cada día.', rating: 4.5, reviews: 98, address: 'Av. 3 #20-45', barrio: 'El Centro', phone: '316 456 7890', whatsapp: true, hours: 'Lun–Sáb · 7:00–20:00', openNow: true, closesAt: '8pm', specialty: 'Carnes', tags: ['Mercado', 'Domicilio'], payments: ['Efectivo', 'Tarjeta'], verified: true, since: '2012', priceLevel: 1 },
  { id: 9, cat: 'ropa', name: 'Modas Valentina', owner: 'Valentina Cruz', desc: 'Ropa para mujer confeccionada a mano. Diseños únicos con telas de calidad a precio accesible.', rating: 4.8, reviews: 78, address: 'C.C. Popular L-34', barrio: 'El Centro', phone: '318 567 8901', whatsapp: true, hours: 'Lun–Sáb · 9:00–19:00', openNow: true, closesAt: '7pm', specialty: 'Confección a medida', tags: ['Confección', 'A medida'], payments: ['Efectivo', 'Nequi'], verified: true, since: '2019', priceLevel: 2 },
  { id: 10, cat: 'ropa', name: 'Zapatos y Más Don Julio', owner: 'Julio Herrera', desc: 'Calzado para toda la familia. Arreglos de calzado y venta de accesorios.', rating: 4.3, reviews: 55, address: 'Calle 10 #6-78', barrio: 'Villa Rosa', phone: '313 678 9012', whatsapp: false, hours: 'Lun–Sáb · 8:00–18:00', openNow: true, closesAt: '6pm', specialty: 'Reparación', tags: ['Zapatería', 'Reparación'], payments: ['Efectivo'], verified: false, since: '2008', priceLevel: 1 },
  { id: 11, cat: 'salud', name: 'Farmacia Popular San Rafael', owner: 'Dra. Ana Bernal', desc: 'Medicamentos genéricos y de marca. Servicio de tensión y glucosa gratuito. Atención personalizada.', rating: 4.9, reviews: 312, address: 'Calle 5 #9-20', barrio: 'El Centro', phone: '319 789 0123', whatsapp: true, hours: 'Lun–Dom · 8:00–22:00', openNow: true, closesAt: '10pm', specialty: 'Farmacia 24h', tags: ['Salud', 'Domicilio'], payments: ['Efectivo', 'Tarjeta', 'Nequi'], verified: true, since: '2014', priceLevel: 2 },
  { id: 12, cat: 'talleres', name: 'Taller El Mecánico Honesto', owner: 'Rodrigo Vargas', desc: 'Servicio mecánico a domicilio y en taller. Motos y carros. Garantía en todos los trabajos.', rating: 4.7, reviews: 143, address: 'Calle Industrial #45-20', barrio: 'El Prado', phone: '321 890 1234', whatsapp: true, hours: 'Lun–Sáb · 8:00–18:00', openNow: true, closesAt: '6pm', specialty: 'Mecánica general', tags: ['Automotriz', 'A domicilio'], payments: ['Efectivo', 'Tarjeta'], verified: true, since: '2011', priceLevel: 2 },
  { id: 13, cat: 'talleres', name: 'Eléctrico Don Jaime', owner: 'Jaime Morales', desc: 'Instalaciones eléctricas residenciales y comerciales. Reparación de electrodomésticos.', rating: 4.6, reviews: 88, address: 'Calle 3 #18-44', barrio: 'La Paz', phone: '322 901 2345', whatsapp: true, hours: 'Lun–Vie · 8:00–17:00', openNow: true, closesAt: '5pm', specialty: 'Eléctrico residencial', tags: ['Eléctrico', 'Urgencias'], payments: ['Efectivo'], verified: false, since: '2016', priceLevel: 2 },
  { id: 14, cat: 'belleza', name: 'Peluquería Estilo Total', owner: 'Sandra López', desc: 'Cortes, tintes, alisados y peinados para toda la familia. Atención con y sin cita.', rating: 4.8, reviews: 189, address: 'Carrera 12 #34-56', barrio: 'Villa Rosa', phone: '323 012 3456', whatsapp: true, hours: 'Mar–Dom · 9:00–19:00', openNow: true, closesAt: '7pm', specialty: 'Tintes y alisados', tags: ['Cabello', 'Sin cita'], payments: ['Efectivo', 'Nequi'], verified: true, since: '2013', priceLevel: 2 },
  { id: 15, cat: 'panaderia', name: 'Panadería El Trigal', owner: 'Miguel Á. Torres', desc: 'Pan artesanal horneado cada mañana. Postres, tortas para ocasiones especiales y café.', rating: 4.9, reviews: 267, address: 'Calle 8 #20-10', barrio: 'La Esperanza', phone: '324 123 4567', whatsapp: true, hours: 'Lun–Dom · 5:00–20:00', openNow: true, closesAt: '8pm', specialty: 'Pan de masa madre', tags: ['Panadería', 'Tortas'], payments: ['Efectivo', 'Nequi', 'Tarjeta'], verified: true, since: '2007', priceLevel: 1 },
  { id: 16, cat: 'electronicos', name: 'Tecno Reparaciones JR', owner: 'Javier Rojas', desc: 'Reparación de celulares, tablets y computadores. Venta de accesorios originales y económicos.', rating: 4.5, reviews: 112, address: 'C.C. Centro L-22', barrio: 'El Centro', phone: '325 234 5678', whatsapp: true, hours: 'Lun–Sáb · 8:00–19:00', openNow: true, closesAt: '7pm', specialty: 'Pantallas y baterías', tags: ['Tecnología', 'Garantía'], payments: ['Efectivo', 'Tarjeta'], verified: true, since: '2017', priceLevel: 2 },
  { id: 17, cat: 'educacion', name: 'Academia Futuro Brillante', owner: 'Prof. Clara Mendoza', desc: 'Clases de refuerzo, matemáticas, español e inglés para niños y jóvenes. Grupos reducidos.', rating: 4.8, reviews: 76, address: 'Calle 15 #7-30', barrio: 'El Centro', phone: '326 345 6789', whatsapp: true, hours: 'Lun–Vie · 14:00–19:00', openNow: false, closesAt: null, specialty: 'Refuerzo escolar', tags: ['Académico', 'Niños'], payments: ['Efectivo', 'Transferencia'], verified: true, since: '2019', priceLevel: 2 },
  { id: 18, cat: 'transporte', name: 'Fletes y Mudanzas El Confiable', owner: 'Hernán Díaz', desc: 'Servicio de fletes locales y mudanzas. Camioneta disponible las 24 horas para emergencias.', rating: 4.6, reviews: 54, address: 'Cra 22 #8-12', barrio: 'El Prado', phone: '327 456 7890', whatsapp: true, hours: '24 horas · 7 días', openNow: true, closesAt: '24h', specialty: 'Mudanzas', tags: ['Logística', '24h'], payments: ['Efectivo', 'Tarjeta'], verified: false, since: '2020', priceLevel: 2 },
  { id: 19, cat: 'artesania', name: 'Arte y Manos Creativas', owner: 'Patricia Suárez', desc: 'Artesanías en madera, cerámica y tejido. Talleres para niños y adultos los fines de semana.', rating: 4.9, reviews: 91, address: 'Casa Cultural, Calle 10', barrio: 'La Esperanza', phone: '328 567 8901', whatsapp: true, hours: 'Mié–Dom · 10:00–17:00', openNow: true, closesAt: '5pm', specialty: 'Cerámica artesanal', tags: ['Arte', 'Talleres'], payments: ['Efectivo', 'Nequi'], verified: true, since: '2016', priceLevel: 2 },
  { id: 20, cat: 'frutas', name: 'Frutería La Cosecha Fresca', owner: 'Esperanza Quiñones', desc: 'Frutas y verduras directas del campo. Domicilios sin costo adicional. Todo fresco cada mañana.', rating: 4.8, reviews: 178, address: 'Mercado Central L-45', barrio: 'El Centro', phone: '329 678 9012', whatsapp: true, hours: 'Lun–Dom · 6:00–12:00', openNow: true, closesAt: '12pm', specialty: 'Frutas del campo', tags: ['Orgánico', 'Domicilio'], payments: ['Efectivo', 'Nequi'], verified: true, since: '2018', priceLevel: 1 },
  { id: 21, cat: 'tecnologia', name: 'Soluciones TIC Popular', owner: 'Diego Ramírez', desc: 'Diseño de páginas web, redes sociales y soporte técnico para pequeños negocios.', rating: 4.7, reviews: 63, address: 'Coworking Centro p2', barrio: 'El Centro', phone: '330 789 0123', whatsapp: true, hours: 'Lun–Vie · 9:00–18:00', openNow: true, closesAt: '6pm', specialty: 'Web para pymes', tags: ['Digital', 'Pymes'], payments: ['Transferencia', 'Tarjeta'], verified: true, since: '2021', priceLevel: 3 },
  { id: 22, cat: 'eventos', name: 'Fiestas y Detalles Don Augusto', owner: 'Augusto Palacios', desc: 'Organización de fiestas, cumpleaños y reuniones. Decoración, sonido y catering incluidos.', rating: 4.5, reviews: 47, address: 'Cra 20 #14-08', barrio: 'Alegría', phone: '331 890 1234', whatsapp: true, hours: 'Con cita previa', openNow: false, closesAt: null, specialty: 'Eventos sociales', tags: ['Eventos', 'Catering'], payments: ['Efectivo', 'Transferencia'], verified: false, since: '2019', priceLevel: 2 },
];

window.DATA = { CATEGORIES, BUSINESSES, BARRIOS };
